pipeline {
    agent { label 'AI_BUILDER' }

    environment {
        DATA_FLOW_HUB_REPO = 'https://git.company-engineering.net/data/data-flow-hub'
    }

    stages {
        stage('Deploy') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'token_gitlab_company_qqtechdataactivities',
                                     usernameVariable: 'GITLAB_CREDENTIALS',
                                     passwordVariable: 'GITLAB_CREDENTIALS_PSW'),
                    usernamePassword(credentialsId: 'cc_github_ipnext',
                                     usernameVariable: 'CC_GITHUB_IPNEXT_CREDENTIALS',
                                     passwordVariable: 'CC_GITHUB_IPNEXT_CREDENTIALS_PSW')
                ]) {
                    dir('data_flow_hub') {
                        git branch: 'main',
                            credentialsId: 'token_gitlab_company_qqtechdataactivities',
                            url: env.DATA_FLOW_HUB_REPO
                    }
                }
            }
        }

        stage('get_tcs_jc_master') {
            steps {
                bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.github_tcs_ingestion.pipelines.get_ipnext_jc_tcs'
            }
        }
    }
}
