pipeline {
    agent { label 'Rivian2' }

    stages {
        stage('Get_Testcases_Ipnext') {
            steps {
                echo 'Running Get_Testcases_Ipnext stage'
                sh 'python etl/run.py'
            }
        }
    }
}
