pipeline {
    agent { label 'AI_BUILDER' }

    options {
        timeout(time: 4, unit: 'HOURS')
    }

    stages {
        stage('Deploy') {
            steps {
                dir('data_flow_hub') {
                    git branch: 'main',
                        credentialsId: 'token_gitlab_company_qqtechdataactivities',
                        url: 'https://git.company-engineering.net/data/data-flow-hub'
                }
            }
        }

        stage('kap_versions') {
            steps {
                bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.redmine_ingestion.pipeline.ingest_kap_versions'
            }
        }

        stage('kap_time_entries') {
            steps {
                bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.redmine_ingestion.pipeline.ingest_kap_time_entries'
            }
        }

        stage('kap_issues') {
            steps {
                bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.redmine_ingestion.pipeline.ingest_kap_issues'
            }
        }

        stage('redmine') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'redmine_training',
                    usernameVariable: 'redmine_usr',
                    passwordVariable: 'redmine_pwd'
                )]) {
                    bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.redmine_ingestion.pipeline.ingest_redmine_training_issues trainingprocess.tech %redmine_pwd% data_team %db_pwd%'
                }
            }
        }
    }
}
