pipeline {
    agent {
        node {
            label 'AI_BUILDER'
            customWorkspace 'D:\\_jenkins_4\\workspace\\redmine_ingestion'
        }
    }

    parameters {
        booleanParam(name: 'DeployExecute', defaultValue: true, description: 'Execute Deploy')
        booleanParam(name: 'redmine', defaultValue: true, description: 'Redmine flag')
    }

    triggers {
        cron('H 2 * * *')
    }

    stages {
        stage('Deploy') {
            steps {
                withCredentials([string(credentialsId: 'kap_api_key', variable: 'KAP_API_KEY')]) {
                    withEnv(['JENKINS_NODE_COOKIE=dontKillMe']) {
                        timeout(time: 4, unit: 'HOURS') {
                            cleanWs()
                            dir('data_flow_hub') {
                                checkout(
                                    scm: [
                                        $class: 'GitSCM',
                                        branches: [[name: 'main']],
                                        userRemoteConfigs: [[
                                            url: 'https://git.company-engineering.net/data/data-flow-hub',
                                            credentialsId: 'token_gitlab_company_qqtechdataactivities'
                                        ]]
                                    ]
                                )
                                bat '''
                                    python -m pip install pipenv
                                    python -m pipenv --rm
                                    python -m pipenv install --ignore-pipfile
                                '''
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
