pipeline {
    agent { label 'windows-python' }

    stages {
        stage('redmine') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'redmine-service-account',
                        usernameVariable: 'REDMINE_USER',
                        passwordVariable: 'REDMINE_PASSWORD'
                    ),
                    usernamePassword(
                        credentialsId: 'db-connector',
                        usernameVariable: 'DB_USER',
                        passwordVariable: 'DB_PASSWORD'
                    )
                ]) {
                    bat '"C:\\Python310\\python.exe" -m pipenv run python -m ingestion.jobs.redmine_ingestion.main'
                }
            }
        }
    }
}
